### ISSUE TITLE
Data from ccfddl.github.io and ccfddl.top are not synchronized

### ISSUE THREAD

**Issue by onefanwu** [ccfddl/ccf-deadlines#202]
Some conferences that have not yet closed appear on ccfddl.github.io but not on ccfddl.top in time, such as vldb 2023.

**Comment by Lukangkang123** [comment]
It has been fixed. Note that, for simplicity, ccfddl.top will only show the most recent one-year conference, when there are two years of conferences not yet closed.

**Comment by onefanwu** [comment]
Thank you for the prompt feedback. ccfddl.top looks very concise and convenient. However, vldb 2024 was showing but now it's gone. If possible, it would be great to show all conferences that are not yet closed in ccfddl.top like ccfddl.github.io.

**Comment by Lukangkang123** [comment]
> Thank you for the prompt feedback. ccfddl.top looks very concise and convenient. However, vldb 2024 was showing but now it's gone. If possible, it would be great to show all conferences that are not yet closed in ccfddl.top like ccfddl.github.io.

Good suggestion. However, this involves a lot of refactoring of the code and I'm trying to figure out how to fix it, which may take some time.

**Comment by onefanwu** [comment]
Haha, if fixing it is time and energy consuming, you can ignore this suggestion. Looking forward to you making ccfddl even better in the near future.

**Comment by Lukangkang123** [comment]
> 

thank you for your support. Because there are very few conferences like vldb that have two years of open deadlines at the same time, I only keep one year of each conference in the database. Maybe your suggestion will be implemented in the future, now I'm thinking about implementing a WeChat applet for ccfddl.

> Haha, if fixing it is time and energy consuming, you can ignore this suggestion. Looking forward to you making ccfddl even better in the near future.

Thank you for your support. Because there are very few conferences like vldb that have two years of open deadlines at the same time, I only keep one year of each conference in the database. Maybe your suggestion will be implemented in the future, now I'm thinking about implementing a WeChat applet for ccfddl.
