### ISSUE TITLE
Some new conferences in CCF 2022 have not been added in the list

### ISSUE THREAD

**Issue by fightingman1** [ccfddl/ccf-deadlines#205]
In 2022, CCF has proposed a new file about recommended conferences and journals, but in the ccfddl website, they do not  in there.  So I  hope the developers would add new conferences and journals in ccfddl website.

**Comment by jacklightChen** [comment]
Sure, the maintainers have already reviewed pull requests according to the new category https://www.ccf.org.cn/Academic_Evaluation/By_category/. However, due to limited development personnel, we may not be able to include all related conferences. If there are any target conferences you interested, opening an issue or submitting a pull request would be a better choice.

**Comment by fightingman1** [comment]
Thank you for your reply, I am interested in Recsys, which is a new conference added in CCF 2022. Its website is [there](https://recsys.acm.org/recsys23/call/#content-tab-1-1).And Interestingly I noticed that a Wechat subscriptions called [CS Conference](https://mp.weixin.qq.com/s/-8CmI-Y_J6k6oxR2wNIWdg) has some coming conferences and their deadlines. I wish it would help you to develop ccfddl website.

**Comment by jacklightChen** [comment]
Thank you for your valuable suggestion, we have added [RecSys 2023](https://github.com/ccfddl/ccf-deadlines/commit/978ab008c03e228822eec8a2809904b17588cc9e) to this project. While we appreciate your recommendation regarding the wechat subscription, we have decided not to rely on it as an external data source due to its unreliability. Instead, we adopt a cooperative approach to maintain conference information to maximize the sharing value without causing any inconvenience to individuals, as graduates are always busy. We appreciate your kind feedback.
